### ISSUE TITLE
Android release build doesn't work with react-native@0.60 (AndroidX support is needed)

### ISSUE THREAD

**Issue by oleksandr-dziuban** [react-native-share/react-native-share#549]
### Steps to reproduce
1. Init new fresh project with latest react-native@0.60.3
2. Install latest react-native-share (with autolinking)
3. Run RELEASE Android build assembling

### Expected behaviour
Release Android build is assembled.

### Actual behaviour
Release Android build is failed.

### Error

```
error: package android.support.v4.content does not exist
[05:45:01]: ▸ import android.support.v4.content.FileProvider;
[05:45:01]: ▸ ^
[05:45:01]: ▸ /Users/distiller/mobile-web-app/node_modules/react-native-share/android/src/main/java/cl/json/RNShareFileProvider.java:5: error: cannot find symbol
[05:45:01]: ▸ public class RNShareFileProvider extends FileProvider {
[05:45:01]: ▸ ^
[05:45:01]: ▸ symbol: class FileProvider
[05:45:01]: ▸ /Users/distiller/mobile-web-app/node_modules/react-native-share/android/src/main/java/cl/json/RNShareModule.java:7: error: package android.support.annotation does not exist
[05:45:01]: ▸ import android.support.annotation.Nullable;
[05:45:01]: ▸ ^
[05:45:01]: ▸ /Users/distiller/mobile-web-app/node_modules/react-native-share/android/src/main/java/cl/json/RNSharePathUtil.java:12: error: package android.support.annotation does not exist
[05:45:01]: ▸ import android.support.annotation.NonNull;
[05:45:01]: ▸ ^
[05:45:01]: ▸ /Users/distiller/mobile-web-app/node_modules/react-native-share/android/src/main/java/cl/json/RNSharePathUtil.java:13: error: package android.support.v4.content does not exist
[05:45:01]: ▸ import android.support.v4.content.CursorLoader;
[05:45:01]: ▸ ^
[05:45:01]: ▸ /Users/distiller/mobile-web-app/node_modules/react-native-share/android/src/main/java/cl/json/RNSharePathUtil.java:14: error: package android.support.v4.content does not exist
[05:45:01]: ▸ import android.support.v4.content.FileProvider;
[05:45:01]: ▸ ^
[05:45:01]: ▸ /Users/distiller/mobile-web-app/node_modules/react-native-share/android/src/main/java/cl/json/RNShareModule.java:126: error: cannot find symbol
[05:45:01]: ▸ public void open(ReadableMap options, @Nullable Callback failureCallback, @Nullable Callback successCallback) {
[05:45:01]: ▸ ^
[05:45:01]: ▸ symbol:   class Nullable
[05:45:01]: ▸ location: class RNShareModule
[05:45:01]: ▸ /Users/distiller/mobile-web-app/node_modules/react-native-share/android/src/main/java/cl/json/RNShareModule.java:126: error: cannot find symbol
[05:45:01]: ▸ public void open(ReadableMap options, @Nullable Callback failureCallback, @Nullable Callback successCallback) {
[05:45:01]: ▸ ^
[05:45:01]: ▸ symbol:   class Nullable
[05:45:01]: ▸ location: class RNShareModule
[05:45:01]: ▸ /Users/distiller/mobile-web-app/node_modules/react-native-share/android/src/main/java/cl/json/RNShareModule.java:143: error: cannot find symbol
[05:45:01]: ▸ public void shareSingle(ReadableMap options, @Nullable Callback failureCallback, @Nullable Callback successCallback) {
[05:45:01]: ▸ ^
[05:45:01]: ▸ symbol:   class Nullable
[05:45:01]: ▸ location: class RNShareModule
[05:45:01]: ▸ /Users/distiller/mobile-web-app/node_modules/react-native-share/android/src/main/java/cl/json/RNShareModule.java:143: error: cannot find symbol
[05:45:01]: ▸ public void shareSingle(ReadableMap options, @Nullable Callback failureCallback, @Nullable Callback successCallback) {
[05:45:01]: ▸ ^
[05:45:01]: ▸ symbol:   class Nullable
[05:45:01]: ▸ location: class RNShareModule
[05:45:01]: ▸ /Users/distiller/mobile-web-app/node_modules/react-native-share/android/src/main/java/cl/json/RNShareModule.java:169: error: cannot find symbol
[05:45:01]: ▸ public void isPackageInstalled(String packagename, @Nullable Callback failureCallback, @Nullable Callback successCallback) {
[05:45:01]: ▸ ^
[05:45:01]: ▸ symbol:   class Nullable
[05:45:01]: ▸ location: class RNShareModule
[05:45:01]: ▸ /Users/distiller/mobile-web-app/node_modules/react-native-share/android/src/main/java/cl/json/RNShareModule.java:169: error: cannot find symbol
[05:45:01]: ▸ public void isPackageInstalled(String packagename, @Nullable Callback failureCallback, @Nullable Callback successCallback) {
[05:45:01]: ▸ ^
[05:45:01]: ▸ symbol:   class Nullable
[05:45:01]: ▸ location: class RNShareModule
[05:45:01]: ▸ /Users/distiller/mobile-web-app/node_modules/react-native-share/android/src/main/java/cl/json/RNShareModule.java:180: error: cannot find symbol
[05:45:01]: ▸ public void isBase64File(String url, @Nullable Callback failureCallback, @Nullable Callback successCallback) {
```

### Environment
- **React Native version**: 0.60.3
- **React Native platform + platform version**: iOS 12.2, Android 9.0 (any 6.0+)

### react-native-share
**Version**: 1.2.1

### Notes
Main breaking change in react-native@0.60 is AndroidX libraries support.
Upgrade of libraries is needed for react-native-share to avoid errors.
As example we can see same changes were merged in https://github.com/react-native-community/react-native-camera/pull/2306

**Comment by guillaume-tgl** [comment]
I didn't have any problem using this plugin with ReactNative 0.60. Do you use the "jetifier" tool as advised [here](https://facebook.github.io/react-native/blog/#androidx-support)?

**Comment by oleksandr-dziuban** [comment]
@guillaume-tgl Hello, I have problem only in release build mode. Dbug works fine. I have a lot of another react-native-... dependencies, project fully migrated to react-native@0.60.3.
"jetifier" is enabled in Android gradle.properties by default now.
Do I need to do some custom steps to use react-native with jetifier?

**Comment by guillaume-tgl** [comment]
I have only tried to run my app in debug. Sorry, I read your issue a bit too quickly, I din't see it was specifically in release mode 🙄

**Comment by oleksandr-dziuban** [comment]
@guillaume-tgl No problems, 👍 yes, problem is present only in release mode

**Comment by arivanandan** [comment]
Not sure if any other errors pop up but to fix that
AndroidManifest.xml
`<provider
        android:name="android.support.v4.content.FileProvider"
        ...`
to
`<provider
        android:name="androidx.core.content.FileProvider"
        ...`

Check: https://developer.android.com/jetpack/androidx/migrate

**Comment by oleksandr-dziuban** [comment]
@arivanandan Hello, could you please specify do we need to modify "AndroidManifest.xml" file in ``react-native-share`` project or in our own project?

**Comment by jgcmarins** [comment]
You can also follow example: https://github.com/react-native-community/react-native-share/blob/master/example/android/app/src/main/AndroidManifest.xml

**Comment by oleksandr-dziuban** [comment]
@guillaume-tgl @arivanandan @jgcmarins @heracek 
Hello guys, I have fixed AndroidX issues in release build and added react-native@0.60.+ support.
Please check PR:
https://github.com/react-native-community/react-native-share/pull/550

I have checked production release builds on CI with my fork, everything is assembling correctly.
Thanks

**Comment by jgcmarins** [comment]
Awesome

**Comment by mikehardy** [comment]
Just to say that the jetifier npm library should handle this for you with current code, but the linked PR is also correct as a migration - just that it is a breaking change (nothing wrong with that! just bump the version + add docs and go) and then people that are stuck on RN0.59 should be advised to use `jetifier -r` as a package.json postinstall. Cheers

**Comment by oleksandr-dziuban** [comment]
@mikehardy I have checked previously, jetifier handle AndroidX Support fine only for Debug build.
In my production project I saw error in release build, so we need to migrate to androidx packages anyway.
For react-native0.59 people just can use react-native-share@1.2.1, it is working fine.
But to support react-native0.50 they need to use react-native-share@2.0.0.
I reflected that in README in my PR.

**Comment by mikehardy** [comment]
The CI for jetifier checks release build specifically because that's where you see resource errors. Something is wrong, it should work.

**Comment by oleksandr-dziuban** [comment]
@mikehardy If you check different react-native community PRs, you will find a lot of PRs to migrate to AndroidX libs, because Jetifier is temporary solution, it will be enabled for transition period only. We need to migrate anyway, like other react-native-... repos

**Comment by mikehardy** [comment]
@oleksandr-dziuban I am the jetifier author, I spent a month discussing it with RN-community in the related issue and testing solutions - I know this :-). What I'm getting at is that your temporary is a different length of time than others temporary. jetifier is supposed to work regardless. And libraries are supposed to migrate regardless

I am absolutely :+1: on the AndroidX pull request (and am on record with the same, on this pull request I think?) - I think it is great and thank you for doing it.

But jetifier should still work. If you can figure out exactly why it is not working, so we can fix it, that would be great.

**Comment by jordangrant** [comment]
<img width="376" alt="Screen Shot 2019-07-19 at 8 22 59 PM" src="https://user-images.githubusercontent.com/7986493/61571759-d0054000-aa63-11e9-9b1c-fde3c8233203.png">
Jetifier missed this :angry-face:
Up and running now though, thanks @oleksandr-dziuban

**Comment by mikehardy** [comment]
@jordangrant that si fascinating - the only instance of the string "CursorLoader" in jetifier is here: https://github.com/mikehardy/jetifier/blob/master/mapping/androidx-class-mapping.csv#L1403

It maps to androidx.loader.content.CursorLoader, which is apparently correct: https://developer.android.com/reference/androidx/loader/content/CursorLoader

If by "Jetifier missed this" you mean the javascript jetifier package that you run in postinstall in package.json did not transform correctly, I would love to see a reproduction that demonstrated this so we could fix it. The name of a react-native library I could use in [the test suite](https://github.com/mikehardy/rn-androidx-demo/blob/master/make-demo.sh) perhaps?

This is maybe unrelated to this current PR (which I like! this library should migrate) but if jetifier has a probem it will cause pain for lots of our fellow developers, I'd love to know and make it work correctly.

**Comment by jordangrant** [comment]
@mikehardy thanks for authoring jetifier! I lost some context on this, but from what I recall: went through https://github.com/react-native-community/react-native-share/pull/550, and went through the diff. The only thing I didn’t already have was CursorLoader. Now, it’s possible I only did Refactor > Migate to AndroidX..
But I did have jetifier in my post-install script so I’m pretty sure it ran npx jetify.

**Comment by jordangrant** [comment]
@mikehardy Here's the verdict:

1. Default import statement was `import android.support.v4.content.CursorLoader;`
2. I manually migrated to AndroidX by: `Refactor > Migrate to AndroidX...`
3. This _improperly_ changed the import statement to `import androidx.core.content.CursorLoader;`
4. When npx jetify ran it wasn't able to change it to` import androidx.loader.content.CursorLoader;`

However, if I run npx jetify first instead of manually Migrating it works as expected.
https://youtu.be/tmxeFpuYgE8

**Comment by oleksandr-dziuban** [comment]
@mikehardy @jordangrant 
I described my issue previously, I have react native project with all files migrated to support react-native@0.60 braking changes. That means I have enabled jetifier by default in gradle settings.
So, I noticed that debug build is working correctly, so jetifier can find and replace all libraries before build automatically. But when I deploy Android app on CircleCI and assemble Release build I see the error from first message in this Issue: `package android.support.v4.content does not exist`.
That means jetifier didn't update libraries automatically for production build.
You can reproduce that easily:
Just create new fresh `react-native@0.60+` project and add `react-native-share@1.2.1` and try to build debug and release Android apps. You will be able to see success debug build and failed release build.
That's why I created this PR and migrated to androidx libraries manually.
New `react-native-share@2.0.0` will conatin androidx support breaking change.
If you need to use previousl android libs with `react-native@<=0.59.10` just please use `react-natice-share@2.0.0` which is reflected in updated README file.
I'm not sure what we are looking here now in this discussion?  Do we want to leave repo as is and just understand why Jetifier doesn't work in Android release build?

**Comment by mikehardy** [comment]
@oleksandr-dziuban we definitely want to update the library for AndroidX, no question there

However, the issue here is still conflating java-jetifier and javascript-jetifier. The status of your android/gradle.properties file is related yes, but separate. It is for java-jetifier

I'm not sure how any support class references could remain in node_modules after javascript-jetifier has run, so this actually appears to be a failure in setup somehow

Anyway, it's odd. I'll add react-native-share to the rn-androidx-demo CI suite for jetifier and investigate, but my general take is still that react-native-share 1.2.x should work just fine with react-native 0.60. I'll prove that assertion though

**Comment by oleksandr-dziuban** [comment]
> @oleksandr-dziuban we definitely want to update the library for AndroidX, no question there
> 
> However, the issue here is still conflating java-jetifier and javascript-jetifier. The status of your android/gradle.properties file is related yes, but separate. It is for java-jetifier
> 
> I'm not sure how any support class references could remain in node_modules after javascript-jetifier has run, so this actually appears to be a failure in setup somehow
> 
> Anyway, it's odd. I'll add react-native-share to the rn-androidx-demo CI suite for jetifier and investigate, but my general take is still that react-native-share 1.2.x should work just fine with react-native 0.60. I'll prove that assertion though

Ok, thanks

**Comment by MateusAndrade** [comment]
Just tested on a fresh project using: 

```json
  "dependencies": {
    "react": "16.8.6",
    "react-native": "0.60.3",
    "react-native-share": "^1.2.1"
  },
```

And it works for both dev/release mode. However, i needed to manually link react-native-share.

**Comment by MateusAndrade** [comment]
For anyone having problems with Android X or react-native >= 0.60, we Just Merge a PR that update react-native-share to 0.60.3 and fix some problems related to Android X. #550 

Please ler us know If you find any problem related to this update. :smiley:

**Comment by mikehardy** [comment]
I just updated the example to RN60 and it seems to work #567 - but yes, in order to use the java object 'ShareApplication' in your MainApplication you have to manually link it for Android, auto-linking doesn't work with that style.

However, with the implementation of an internal FileProvider via #490 it is not necessary to import or implement anything in MainApplication and auto-linking should work. I demonstrate this in #570
